Fixes Get Events API null total
FrigadeHQ/trench pull request #27
Opened 2024-11-24 08:53 UTC by tuminzee

Fixes https://github.com/FrigadeHQ/trench/issues/13
Earlier the total was returning a hardcoded `null` value, I changed it to get count on the where clause

``` ts
const total = await this.clickhouse.queryResults(totalQuery, workspace.databaseName)
const totalCount = total?.[0]?.count || null
```

2024-11-24 08:55 UTC, tuminzee commented
@christianmat I am not sure if I am supposed to write tests for it. Anyways do let me know what you think about it.

2024-11-25 17:29 UTC, christianmat commented
Hey @tuminzee, thanks for this PR. Please see the guide on contributing re: tests: https://docs.trench.dev/contributing

One thing we need to fix here is that the `total` is not meant to simply equal the length of the array, it's supposed to be the total amount of records matching the query string. It is meant to be used for pagination so you know how many results you have. The real solution should be to do a separate query to clickhouse in parallel that counts the number of rows that matches the query.

2024-11-25 17:31 UTC, tuminzee commented
@christianmat I have a made a separate query for calculating the total. It is not a length fn.

I will check the contribution guidelines

2024-11-27 01:43 UTC, christianmat requested changes
Please add e2e tests as well that test that this field works. See other e2e tests for examples.

2024-11-27 01:43 UTC, christianmat commented on apps/trench/src/events/events.dao.ts
> +      const totalCount = total?.[0]?.count || null
Can you change this to be `Promise.all` such that it executes in parallel?

2024-12-02 11:16 UTC, tuminzee commented
> Please add e2e tests as well that test that this field works. See other e2e tests for examples.

Yes I will do that

2024-12-02 23:08 UTC, tuminzee commented
[`waitForQueryResults`](https://github.com/FrigadeHQ/trench/blob/2aaa3e784e1fd869664033b2f5793e9928ce4548/apps/trench/test/e2e/utils.ts#L48) function should return the complete `res.body` instead of just `res.body.results` since we need to test other response properties like [`total`](https://github.com/FrigadeHQ/trench/blob/2aaa3e784e1fd869664033b2f5793e9928ce4548/apps/trench/src/events/events.dao.ts#L115C9-L115C14)


Questions for review:
1. Should I update all affected tests to include `total` property validation, or should we keep this as a separate enhancement?
2. If no results are found the query would always return a [timeout error](https://github.com/FrigadeHQ/trench/blob/2aaa3e784e1fd869664033b2f5793e9928ce4548/apps/trench/src/events/events.dao.ts#L115C9-L115C14), shouldn't it just return a plain response?

2024-12-04 00:47 UTC, christianmat commented
> [`waitForQueryResults`](https://github.com/FrigadeHQ/trench/blob/2aaa3e784e1fd869664033b2f5793e9928ce4548/apps/trench/test/e2e/utils.ts#L48) function should return the complete `res.body` instead of just `res.body.results` since we need to test other response properties like [`total`](https://github.com/FrigadeHQ/trench/blob/2aaa3e784e1fd869664033b2f5793e9928ce4548/apps/trench/src/events/events.dao.ts#L115C9-L115C14)
> 
> Questions for review:
> 
> 1. Should I update all affected tests to include `total` property validation, or should we keep this as a separate enhancement?
> 2. If no results are found the query would always return a [timeout error](https://github.com/FrigadeHQ/trench/blob/2aaa3e784e1fd869664033b2f5793e9928ce4548/apps/trench/src/events/events.dao.ts#L115C9-L115C14), shouldn't it just return a plain response?

1. Yes, please update all the existing tests to account for the new `total` behavior.
2. Not sure what you mean. It currently returns an empty array if no results are returned, it doesn't throw an error (see test screenshot below)
![image](https://github.com/user-attachments/assets/77e8527e-a8a0-4e80-8bbe-8f36c64909cd)

2024-12-04 08:35 UTC, tuminzee commented
- I have updated the tests to include the [total](https://github.com/tuminzee/trench/blob/754ec18743c124f10178d50a2a0834ab55035cba/apps/trench/test/e2e/utils.ts#L55-L57) property.
- Regarding the timeout error: I apologize for not clarifying earlier—this issue occurs only in the e2e tests. [waitForQueryResults](https://github.com/tuminzee/trench/blob/754ec18743c124f10178d50a2a0834ab55035cba/apps/trench/test/e2e/utils.ts#L48-L63): It currently throws an error if no results are found. Should this be the expected behavior, or should we modify it to return an empty array instead? Let me know your preference, and I can adjust accordingly. I have added a test to demonstrate this [here](https://github.com/tuminzee/trench/blob/c798969220835ab7d7e085ac76c92618c02a9c83/apps/trench/test/e2e/events.e2e.test.ts#L91-L95)

2024-12-09 23:31 UTC, christianmat approved these changes

2024-12-09 23:31 UTC, merged